package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblCliente generated by hbm2java
 */
public class TblCliente  implements java.io.Serializable {


     private Integer clienteCodigo;
     private String clienteGenero;
     private String clientePrimeironome;
     private String clienteUltimonome;
     private String clienteEmail;
     private String clienteLogin;
     private String clienteSenha;
     private String clienteTelefone;
     private String clienteEndereco1;
     private String clienteEndereco2;
     private String clienteCidade;
     private String clienteEstado;
     private String clientePais;
     private Boolean clienteAdm;
     private Set tblPedidos = new HashSet(0);
     private Set tblMetodosPagamentoClientes = new HashSet(0);

    public TblCliente() {
    }

	
    public TblCliente(String clienteGenero, String clientePrimeironome, String clienteUltimonome, String clienteEmail, String clienteLogin, String clienteSenha, String clienteTelefone, String clienteEndereco1, String clienteCidade, String clienteEstado, String clientePais) {
        this.clienteGenero = clienteGenero;
        this.clientePrimeironome = clientePrimeironome;
        this.clienteUltimonome = clienteUltimonome;
        this.clienteEmail = clienteEmail;
        this.clienteLogin = clienteLogin;
        this.clienteSenha = clienteSenha;
        this.clienteTelefone = clienteTelefone;
        this.clienteEndereco1 = clienteEndereco1;
        this.clienteCidade = clienteCidade;
        this.clienteEstado = clienteEstado;
        this.clientePais = clientePais;
    }
    public TblCliente(String clienteGenero, String clientePrimeironome, String clienteUltimonome, String clienteEmail, String clienteLogin, String clienteSenha, String clienteTelefone, String clienteEndereco1, String clienteEndereco2, String clienteCidade, String clienteEstado, String clientePais, Boolean clienteAdm, Set tblPedidos, Set tblMetodosPagamentoClientes) {
       this.clienteGenero = clienteGenero;
       this.clientePrimeironome = clientePrimeironome;
       this.clienteUltimonome = clienteUltimonome;
       this.clienteEmail = clienteEmail;
       this.clienteLogin = clienteLogin;
       this.clienteSenha = clienteSenha;
       this.clienteTelefone = clienteTelefone;
       this.clienteEndereco1 = clienteEndereco1;
       this.clienteEndereco2 = clienteEndereco2;
       this.clienteCidade = clienteCidade;
       this.clienteEstado = clienteEstado;
       this.clientePais = clientePais;
       this.clienteAdm = clienteAdm;
       this.tblPedidos = tblPedidos;
       this.tblMetodosPagamentoClientes = tblMetodosPagamentoClientes;
    }
   
    public Integer getClienteCodigo() {
        return this.clienteCodigo;
    }
    
    public void setClienteCodigo(Integer clienteCodigo) {
        this.clienteCodigo = clienteCodigo;
    }
    public String getClienteGenero() {
        return this.clienteGenero;
    }
    
    public void setClienteGenero(String clienteGenero) {
        this.clienteGenero = clienteGenero;
    }
    public String getClientePrimeironome() {
        return this.clientePrimeironome;
    }
    
    public void setClientePrimeironome(String clientePrimeironome) {
        this.clientePrimeironome = clientePrimeironome;
    }
    public String getClienteUltimonome() {
        return this.clienteUltimonome;
    }
    
    public void setClienteUltimonome(String clienteUltimonome) {
        this.clienteUltimonome = clienteUltimonome;
    }
    public String getClienteEmail() {
        return this.clienteEmail;
    }
    
    public void setClienteEmail(String clienteEmail) {
        this.clienteEmail = clienteEmail;
    }
    public String getClienteLogin() {
        return this.clienteLogin;
    }
    
    public void setClienteLogin(String clienteLogin) {
        this.clienteLogin = clienteLogin;
    }
    public String getClienteSenha() {
        return this.clienteSenha;
    }
    
    public void setClienteSenha(String clienteSenha) {
        this.clienteSenha = clienteSenha;
    }
    public String getClienteTelefone() {
        return this.clienteTelefone;
    }
    
    public void setClienteTelefone(String clienteTelefone) {
        this.clienteTelefone = clienteTelefone;
    }
    public String getClienteEndereco1() {
        return this.clienteEndereco1;
    }
    
    public void setClienteEndereco1(String clienteEndereco1) {
        this.clienteEndereco1 = clienteEndereco1;
    }
    public String getClienteEndereco2() {
        return this.clienteEndereco2;
    }
    
    public void setClienteEndereco2(String clienteEndereco2) {
        this.clienteEndereco2 = clienteEndereco2;
    }
    public String getClienteCidade() {
        return this.clienteCidade;
    }
    
    public void setClienteCidade(String clienteCidade) {
        this.clienteCidade = clienteCidade;
    }
    public String getClienteEstado() {
        return this.clienteEstado;
    }
    
    public void setClienteEstado(String clienteEstado) {
        this.clienteEstado = clienteEstado;
    }
    public String getClientePais() {
        return this.clientePais;
    }
    
    public void setClientePais(String clientePais) {
        this.clientePais = clientePais;
    }
    public Boolean getClienteAdm() {
        return this.clienteAdm;
    }
    
    public void setClienteAdm(Boolean clienteAdm) {
        this.clienteAdm = clienteAdm;
    }
    public Set getTblPedidos() {
        return this.tblPedidos;
    }
    
    public void setTblPedidos(Set tblPedidos) {
        this.tblPedidos = tblPedidos;
    }
    public Set getTblMetodosPagamentoClientes() {
        return this.tblMetodosPagamentoClientes;
    }
    
    public void setTblMetodosPagamentoClientes(Set tblMetodosPagamentoClientes) {
        this.tblMetodosPagamentoClientes = tblMetodosPagamentoClientes;
    }




}


