package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblEnvios generated by hbm2java
 */
public class TblEnvios  implements java.io.Serializable {


     private Integer envioCodigo;
     private TblFatura tblFatura;
     private TblPedidos tblPedidos;
     private String envioRastreio;
     private String envioData;
     private Set tblItensPedidos = new HashSet(0);

    public TblEnvios() {
    }

	
    public TblEnvios(TblFatura tblFatura, TblPedidos tblPedidos, String envioRastreio, String envioData) {
        this.tblFatura = tblFatura;
        this.tblPedidos = tblPedidos;
        this.envioRastreio = envioRastreio;
        this.envioData = envioData;
    }
    public TblEnvios(TblFatura tblFatura, TblPedidos tblPedidos, String envioRastreio, String envioData, Set tblItensPedidos) {
       this.tblFatura = tblFatura;
       this.tblPedidos = tblPedidos;
       this.envioRastreio = envioRastreio;
       this.envioData = envioData;
       this.tblItensPedidos = tblItensPedidos;
    }
   
    public Integer getEnvioCodigo() {
        return this.envioCodigo;
    }
    
    public void setEnvioCodigo(Integer envioCodigo) {
        this.envioCodigo = envioCodigo;
    }
    public TblFatura getTblFatura() {
        return this.tblFatura;
    }
    
    public void setTblFatura(TblFatura tblFatura) {
        this.tblFatura = tblFatura;
    }
    public TblPedidos getTblPedidos() {
        return this.tblPedidos;
    }
    
    public void setTblPedidos(TblPedidos tblPedidos) {
        this.tblPedidos = tblPedidos;
    }
    public String getEnvioRastreio() {
        return this.envioRastreio;
    }
    
    public void setEnvioRastreio(String envioRastreio) {
        this.envioRastreio = envioRastreio;
    }
    public String getEnvioData() {
        return this.envioData;
    }
    
    public void setEnvioData(String envioData) {
        this.envioData = envioData;
    }
    public Set getTblItensPedidos() {
        return this.tblItensPedidos;
    }
    
    public void setTblItensPedidos(Set tblItensPedidos) {
        this.tblItensPedidos = tblItensPedidos;
    }




}


