package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblFatura generated by hbm2java
 */
public class TblFatura  implements java.io.Serializable {


     private Integer faturaCodigo;
     private TblPedidos tblPedidos;
     private TblRefFaturaStatus tblRefFaturaStatus;
     private String faturaData;
     private String faturaDetalhes;
     private Set tblEnvioses = new HashSet(0);
     private Set tblPagamentoses = new HashSet(0);

    public TblFatura() {
    }

	
    public TblFatura(TblPedidos tblPedidos, TblRefFaturaStatus tblRefFaturaStatus) {
        this.tblPedidos = tblPedidos;
        this.tblRefFaturaStatus = tblRefFaturaStatus;
    }
    public TblFatura(TblPedidos tblPedidos, TblRefFaturaStatus tblRefFaturaStatus, String faturaData, String faturaDetalhes, Set tblEnvioses, Set tblPagamentoses) {
       this.tblPedidos = tblPedidos;
       this.tblRefFaturaStatus = tblRefFaturaStatus;
       this.faturaData = faturaData;
       this.faturaDetalhes = faturaDetalhes;
       this.tblEnvioses = tblEnvioses;
       this.tblPagamentoses = tblPagamentoses;
    }
   
    public Integer getFaturaCodigo() {
        return this.faturaCodigo;
    }
    
    public void setFaturaCodigo(Integer faturaCodigo) {
        this.faturaCodigo = faturaCodigo;
    }
    public TblPedidos getTblPedidos() {
        return this.tblPedidos;
    }
    
    public void setTblPedidos(TblPedidos tblPedidos) {
        this.tblPedidos = tblPedidos;
    }
    public TblRefFaturaStatus getTblRefFaturaStatus() {
        return this.tblRefFaturaStatus;
    }
    
    public void setTblRefFaturaStatus(TblRefFaturaStatus tblRefFaturaStatus) {
        this.tblRefFaturaStatus = tblRefFaturaStatus;
    }
    public String getFaturaData() {
        return this.faturaData;
    }
    
    public void setFaturaData(String faturaData) {
        this.faturaData = faturaData;
    }
    public String getFaturaDetalhes() {
        return this.faturaDetalhes;
    }
    
    public void setFaturaDetalhes(String faturaDetalhes) {
        this.faturaDetalhes = faturaDetalhes;
    }
    public Set getTblEnvioses() {
        return this.tblEnvioses;
    }
    
    public void setTblEnvioses(Set tblEnvioses) {
        this.tblEnvioses = tblEnvioses;
    }
    public Set getTblPagamentoses() {
        return this.tblPagamentoses;
    }
    
    public void setTblPagamentoses(Set tblPagamentoses) {
        this.tblPagamentoses = tblPagamentoses;
    }




}


