package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblItensPedido generated by hbm2java
 */
public class TblItensPedido  implements java.io.Serializable {


     private Integer itensPedidoCodigo;
     private TblPedidoItemStatus tblPedidoItemStatus;
     private TblPedidos tblPedidos;
     private TblProduto tblProduto;
     private String itensPedidoQuantidade;
     private String itensPedidoPreco;
     private Set tblEnvioses = new HashSet(0);

    public TblItensPedido() {
    }

	
    public TblItensPedido(TblPedidoItemStatus tblPedidoItemStatus, TblPedidos tblPedidos, TblProduto tblProduto) {
        this.tblPedidoItemStatus = tblPedidoItemStatus;
        this.tblPedidos = tblPedidos;
        this.tblProduto = tblProduto;
    }
    public TblItensPedido(TblPedidoItemStatus tblPedidoItemStatus, TblPedidos tblPedidos, TblProduto tblProduto, String itensPedidoQuantidade, String itensPedidoPreco, Set tblEnvioses) {
       this.tblPedidoItemStatus = tblPedidoItemStatus;
       this.tblPedidos = tblPedidos;
       this.tblProduto = tblProduto;
       this.itensPedidoQuantidade = itensPedidoQuantidade;
       this.itensPedidoPreco = itensPedidoPreco;
       this.tblEnvioses = tblEnvioses;
    }
   
    public Integer getItensPedidoCodigo() {
        return this.itensPedidoCodigo;
    }
    
    public void setItensPedidoCodigo(Integer itensPedidoCodigo) {
        this.itensPedidoCodigo = itensPedidoCodigo;
    }
    public TblPedidoItemStatus getTblPedidoItemStatus() {
        return this.tblPedidoItemStatus;
    }
    
    public void setTblPedidoItemStatus(TblPedidoItemStatus tblPedidoItemStatus) {
        this.tblPedidoItemStatus = tblPedidoItemStatus;
    }
    public TblPedidos getTblPedidos() {
        return this.tblPedidos;
    }
    
    public void setTblPedidos(TblPedidos tblPedidos) {
        this.tblPedidos = tblPedidos;
    }
    public TblProduto getTblProduto() {
        return this.tblProduto;
    }
    
    public void setTblProduto(TblProduto tblProduto) {
        this.tblProduto = tblProduto;
    }
    public String getItensPedidoQuantidade() {
        return this.itensPedidoQuantidade;
    }
    
    public void setItensPedidoQuantidade(String itensPedidoQuantidade) {
        this.itensPedidoQuantidade = itensPedidoQuantidade;
    }
    public String getItensPedidoPreco() {
        return this.itensPedidoPreco;
    }
    
    public void setItensPedidoPreco(String itensPedidoPreco) {
        this.itensPedidoPreco = itensPedidoPreco;
    }
    public Set getTblEnvioses() {
        return this.tblEnvioses;
    }
    
    public void setTblEnvioses(Set tblEnvioses) {
        this.tblEnvioses = tblEnvioses;
    }




}


