package Entidades;
// Generated 31/03/2015 20:14:15 by Hibernate Tools 4.3.1



/**
 * TblPagamentos generated by hbm2java
 */
public class TblPagamentos  implements java.io.Serializable {


     private Integer pagamentosCodigo;
     private TblFatura tblFatura;
     private String pagamentosData;
     private String pagamentosQuantia;

    public TblPagamentos() {
    }

	
    public TblPagamentos(TblFatura tblFatura, String pagamentosQuantia) {
        this.tblFatura = tblFatura;
        this.pagamentosQuantia = pagamentosQuantia;
    }
    public TblPagamentos(TblFatura tblFatura, String pagamentosData, String pagamentosQuantia) {
       this.tblFatura = tblFatura;
       this.pagamentosData = pagamentosData;
       this.pagamentosQuantia = pagamentosQuantia;
    }
   
    public Integer getPagamentosCodigo() {
        return this.pagamentosCodigo;
    }
    
    public void setPagamentosCodigo(Integer pagamentosCodigo) {
        this.pagamentosCodigo = pagamentosCodigo;
    }
    public TblFatura getTblFatura() {
        return this.tblFatura;
    }
    
    public void setTblFatura(TblFatura tblFatura) {
        this.tblFatura = tblFatura;
    }
    public String getPagamentosData() {
        return this.pagamentosData;
    }
    
    public void setPagamentosData(String pagamentosData) {
        this.pagamentosData = pagamentosData;
    }
    public String getPagamentosQuantia() {
        return this.pagamentosQuantia;
    }
    
    public void setPagamentosQuantia(String pagamentosQuantia) {
        this.pagamentosQuantia = pagamentosQuantia;
    }




}


